import React,{useEffect,useState} from "react";import{createRoot}from"react-dom/client";import"./style.css";
const API="/api"; const stages=["Slot Booked","Arrival","Gate Verified","Weighing","Quality Assessment","Procurement Accepted","Payment Initiated","Payment Confirmed"];
function App(){const[tab,setTab]=useState("farmer"),[farmer,setFarmer]=useState(null),[centres,setCentres]=useState([]),[allocs,setAllocs]=useState([]),[dash,setDash]=useState(null),[selected,setSelected]=useState({}),[events,setEvents]=useState({});
const load=async()=>{setFarmer(await (await fetch(API+"/farmer")).json());setCentres(await (await fetch(API+"/centres")).json());setAllocs(await (await fetch(API+"/allocations")).json());setDash(await (await fetch(API+"/dashboard")).json())};useEffect(()=>{load()},[]);
const allocate=async()=>{let items=Object.entries(selected).filter(([_,v])=>v>0).map(([id,qty])=>({centre_id:+id,qty:+qty}));if(!items.length)return alert("Enter quantity");let total=items.reduce((a,x)=>a+x.qty,0);if(total>farmer.eligible_qty)return alert("Quantity exceeds eligibility");await fetch(API+"/allocate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({farmer_id:farmer.id||1,items})});load();alert("Quota reserved and slots issued.")};
const weather=async()=>{await fetch(API+"/weather-event",{method:"POST"});load();alert("Weather event simulated. Check the booking timeline.")};
const addEvent=async(a,e)=>{await fetch(API+"/event",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({allocation_id:a.id,event:e})});load()};
return <><header><div className="brand">🌾 Krishi <b>Sarathi</b><small>SIH26032</small></div><nav>{["farmer","centre","government"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)}>{x==="farmer"?"👨‍🌾 Farmer":x==="centre"?"🏭 Centre":"🏛 Government"}</button>)}</nav></header>
<main>{tab==="farmer"&&<><section className="hero"><div><p className="eyebrow">SMART PROCUREMENT ORCHESTRATION</p><h1>Sell smarter.<br/><span>Wait less.</span></h1><p>One transparent workflow from Kisan ID to payment.</p></div><div className="profile"><b>{farmer?.name||"Ramesh Kumar"}</b><small>Kisan ID · {farmer?.kisan_id}</small><strong>{farmer?.eligible_qty||10} T eligible</strong></div></section>
<div className="grid"><section className="card wide"><h2>Smart Centre Recommendation</h2><p className="muted">AI-style explainable score using queue, quota, weather and processing capacity.</p>{centres.map(c=><div className="centre"><div><b>{c.name}</b><small>{c.location} · Queue {c.queue} · Weather {c.weather}/100</small></div><span className="score">{c.score}/100</span><input type="number" min="0" max={c.quota} placeholder="Tonnes" value={selected[c.id]||""} onChange={e=>setSelected({...selected,[c.id]:e.target.value})}/></div>)}<button className="primary" onClick={allocate}>Reserve Quota + Book Slots →</button></section>
<section className="card"><h2>How the score works</h2><div className="bars"><p>Distance <i style={{width:"92%"}}/></p><p>Queue <i style={{width:"84%"}}/></p><p>Capacity <i style={{width:"90%"}}/></p><p>Quota <i style={{width:"88%"}}/></p><p>Weather <i style={{width:"82%"}}/></p></div><div className="callout">AI recommends. <b>Farmer remains in control.</b></div></section></div>
<section className="card"><h2>Live Procurement Timeline</h2>{allocs.length?<div className="allocs">{allocs.map(a=><div className="allocation"><div><b>{a.qty} T · {a.centre}</b><small>{a.status} · QR {a.qr}</small></div><div className="timeline">{(events[a.id]||[{event:"Slot Booked"}]).map(e=><span>● {e.event}</span>)}</div><button onClick={async()=>{let ev=await (await fetch(API+"/events/"+a.id)).json();setEvents({...events,[a.id]:ev})}}>Refresh</button></div>)}</div>:<p className="muted">No booking yet. Allocate wheat above to start the live demo.</p>}</section>
<div className="demo"><button onClick={weather}>⚡ Simulate Centre B Weather Alert</button><span>Demo control: triggers risk 89/100 and automatic reallocation.</span></div></>}
{tab==="centre"&&<Centre allocs={allocs} addEvent={addEvent}/>}
{tab==="government"&&<Gov dash={dash} weather={weather}/>}</main></>}
function Centre({allocs,addEvent}){return <><div className="pagehead"><p className="eyebrow">CENTRE OPERATIONS</p><h1>Centre B Command Desk</h1></div><div className="stats"><Stat t="Today's bookings" v={allocs.length}/><Stat t="Live queue" v="18"/><Stat t="Capacity" v="75%"/><Stat t="Weather risk" v="22/100"/></div><section className="card"><h2>Procurement Queue</h2>{allocs.map(a=><div className="row"><b>{a.qty}T · {a.centre}</b><span>{a.status}</span><button onClick={()=>addEvent(a,"Arrival")}>Arrival</button><button onClick={()=>addEvent(a,"Weighing")}>Weigh</button><button onClick={()=>addEvent(a,"Quality Assessment")}>Quality</button><button onClick={()=>addEvent(a,"Procurement Accepted")}>Accept</button><button onClick={()=>addEvent(a,"Payment Initiated")}>Payment</button><button onClick={()=>addEvent(a,"Payment Confirmed")}>Paid</button></div>)}</section></>}
function Gov({dash,weather}){return <><div className="pagehead"><p className="eyebrow">GOVERNMENT INTELLIGENCE</p><h1>Procurement Command Centre</h1></div><div className="stats"><Stat t="Farmers" v={dash?.farmers||0}/><Stat t="Allocations" v={dash?.allocations||0}/><Stat t="Tonnes allocated" v={dash?.tonnes||0}/><Stat t="Network queue" v={dash?.queue||0}/></div><div className="grid"><section className="card wide"><h2>Centre Health Network</h2>{(dash?.centres||[]).map(c=><div className="health"><b>{c.name}</b><span>Queue {c.queue}</span><span>Quota {c.quota}T</span><span>Weather {c.weather}/100</span><em>{c.weather>80?"⚠ Attention":"● Healthy"}</em></div>)}</section><section className="card"><h2>Priority Alerts</h2>{(dash?.alerts||[]).map(a=><div className="alert">⚠️ <b>{a.type}</b><p>{a.message}</p></div>)}<button className="primary" onClick={weather}>Simulate Weather Alert</button></section></div></>}
function Stat({t,v}){return <div className="stat"><small>{t}</small><strong>{v}</strong></div>}createRoot(document.getElementById("root")).render(<App/>);